### ISSUE TITLE
Q: the Definition of parameters of EM-IRT

### ISSUE THREAD

**Issue by CSLiJT** [bigdata-ustc/EduCDM#19]
I tried running the EM-IRT code as a baseline model, but the definition of some parameters confused me...
I wonder the type and meaning of the parameter R, skip_value and D(which is initialized to 1.702).
Thank you!

**Comment by tswsxk** [comment]
@Ljyustc

**Comment by Ljyustc** [comment]
Thanks for your comment! Details of these parameters are:
1、R(numpy.array): response matrix, shape = (number of students, number of exercises).
R contains all training records, e.g. R_ij=1 indicates that student i answered right on exercise j,  and R_ij = 0 otherwise.
2、skip_value(int): skip value in response matrix R.
We use 1 or 0 to indicate right or wrong answer in training data. However, a student may not answer all exercises, thus we have to mark these unrecorded positions in response matrix R, prevent their influence on training. For example, if skip_value is set as -1, then you can set R_ij=-1 if student i didn't answer exercise j.
3、D(float):  D is an empirical scaling constant in IRT model, which is commonly set as 1.702 or 1.7 (Please refer "Item Response Theory: Application to Psychological Measurement", Dorsey Press, 1983).

**Comment by CSLiJT** [comment]
I get the point. Thanks a lot!
